#!/usr/bin/env bash

usage() {
  cat 1>&2 <<EOF
play.sh
The playbook index

USAGE:
    play.sh [FLAGS] [OPTIONS]

FLAGS:
    -h, --help      Print this help information
    -d, --dry-run   Verify playbook with --check; don't change anything
    -l, --local     Use local playbook; don't download anything
    -x, --persist   Persist temporary runtime directory (for debugging)

OPTIONS:
    -p, --profile <profile>   Installation profile (see PROFILES)
    -b, --branch  <branch>    Alternate playbook branch (default: master)

PROFILES:
    thinclient
    webclient
    workstation
EOF
}

# Constants
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DEFAULT_BRANCH=master
SOURCE=https://raw.githubusercontent.com/lenzomj/dotfiles

DEFAULT_PROFILE=WEBCLIENT

# shellcheck disable=SC2034 # Ignore unused variable
getdockercreds=(
playbook-getdockercreds.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
getherokucli=(
playbook-getherokucli.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
getnodejs=(
playbook-getnodejs.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
getpython=(
playbook-getpython.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
getrustup=(
playbook-getrustup.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
oxidize=(
playbook-oxidize.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
protoqube=(
playbook-protoqube.yml
tasks/provision-setup.yml
tasks/provision-common.yml
tasks/provision-security.yml
tasks/provision-devtools.yml
tasks/provision-avrtools.yml
tasks/provision-cleanup.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
signalqube=(
playbook-signalqube.yml
tasks/provision-setup.yml
tasks/provision-signal.yml
tasks/provision-cleanup.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
thinqube=(
playbook-thinqube.yml
tasks/provision-setup.yml
tasks/provision-certs.yml
tasks/provision-chrome.yml
tasks/provision-cleanup.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
webqube=(
playbook-webqube.yml
tasks/provision-setup.yml
tasks/provision-certs.yml
tasks/provision-chrome.yml
tasks/provision-cleanup.yml
)

# shellcheck disable=SC2034 # Ignore unused variable
workqube=(
playbook-workqube.yml
tasks/provision-setup.yml
tasks/provision-common.yml
tasks/provision-security.yml
tasks/provision-devtools.yml
tasks/provision-pybuilder.yml
tasks/provision-certs.yml
tasks/provision-chrome.yml
tasks/provision-docker.yml
tasks/provision-office.yml
tasks/provision-cleanup.yml
)

main() {
  local _local=0
  local _dryrun=0
  local _persist=0
  local _profile=${DEFAULT_PROFILE}
  local _branch=${DEFAULT_BRANCH}
  local _tmpdir
  local _list

  while [[ $# -gt 0 ]]; do
    case "${1}" in
      --help|-h)
        usage
        exit 0
        ;;
      --dry-run|-d)
        _dryrun=1
        shift
        ;;
      --local|-l)
        _local=1
        shift
        ;;
      --persist|-x)
        _persist=1
        shift
        ;;
      --profile|-p)
        _profile=$(echo "${2}" | tr '[:upper:]' '[:lower:]')
        shift 2
        [[ -z "${!_profile}" ]] && \
          err "unknown profile '${_profile}'"
        ;;
      --branch|-b)
        _branch=${2}
        shift 2
        ;;
      *)
        err "unkown flag or option '${1}'"
    esac
  done

  require curl
  require ansible-playbook

  _tmpdir="$(try mktemp -d)"

  mkdir -p "${_tmpdir}/tasks"

  _list="${_profile}[@]"
  for file in "${!_list}"; do
    if [[ ${_local} -eq 0 ]]; then
      try curl -sS \
               -H "Cache-Control: no-cache, no-store, must-revalidate" \
               -H "Pragma: no-cache" \
               -H "Expires: 0" \
          "${SOURCE}/${_branch}/playbook/${file}" -o "${_tmpdir}/${file}"
    else
      try cp "${SCRIPT_DIR}/${file}" "${_tmpdir}/${file}"
    fi
  done

  describe_inventory "${_tmpdir}"

  pushd "${_tmpdir}" &> /dev/null || exit;
    if [[ ${_dryrun} -eq 0 ]]; then
      try ansible-playbook -i hosts "playbook-${_profile}.yml"
    else
      try ansible-playbook -i hosts "playbook-${_profile}.yml" --check --diff
    fi
  popd &> /dev/null || exit;

  if [[ ${_persist} -eq 0 ]]; then
    try rm -rf "${_tmpdir}"
  fi
}

describe_inventory() {
  cat << EOF > "${1}/hosts"
localhost

[local]
localhost

[local:vars]
ansible_connection=local
ansible_python_interpreter="/usr/bin/env python3"
EOF
}

say() {
  printf 'play: %s\n' "$1"
}

err() {
  say "$1" >&2
  exit 1
}

find_cmd() {
  command -v "$1" > /dev/null 2>&1
}

require() {
  if ! find_cmd "$1"; then
    err "need '$1' (command not found)"
  fi
}

try() {
  if ! "$@"; then err "command failed: $*"; fi
}

main "$@" || exit 1
